Add Arduino sample documentation
Azure/iotedge-lorawan-starterkit pull request #1159
Opened 2021-12-24 13:05 UTC by Mandur

# PR for issue #1013

## What is being addressed

Adding documentation on the arduino required changes. 
If there is any feedback there, I will adress it after my vacations.

2021-12-24 13:22 UTC, roel4ez requested changes
There is already a short document on the Arduino Sample: https://azure.github.io/iotedge-lorawan-starterkit/dev/samples/arduino/

Not sure if that one should be extended, or a new article should be created. Could be under the same `Samples` directory.

Also, you'll need to add the file to `mkdocs.yml` > `nav` section to make it show up in the docs.

2021-12-24 13:22 UTC, roel4ez commented on docs/tools/arduino-samples.md
> +There are multuple scenarios where we would want to have the librairies be modified (listed here below). To access the local installation open your arduino IDE, go to File -> Preferences and click on
```suggestion
There are multiple scenarios where we would want to have the libraries be modified (listed here below). To access the local installation, open your Arduino IDE, go to File -> Preferences and click on the line after "more preference can be edited directly in the file".
```

2021-12-24 13:22 UTC, roel4ez commented on docs/tools/arduino-samples.md
> +Go next to the path "packages/Seeeduino/hardware/samd/1.8.2/libraries/LoRaWan and open LoRaWan.cpp and LoRaWan.h in a text editor.
```suggestion
Go next to the path `packages/Seeeduino/hardware/samd/1.8.2/libraries/LoRaWan` and open `LoRaWan.cpp` and `LoRaWan.h` in a text editor.
```

2021-12-24 13:22 UTC, roel4ez commented on docs/tools/arduino-samples.md
> +        void setChannelON(unsigned char channel);
```suggestion
void setChannelON(unsigned char channel);
```

2021-12-24 13:22 UTC, roel4ez commented on docs/tools/arduino-samples.md
> +        void setChannelOFF(unsigned char channel);
```suggestion
void setChannelOFF(unsigned char channel);
```

2022-01-09 14:28 UTC, Mandur commented on docs/tools/arduino-samples.md
> +Go next to the path "packages/Seeeduino/hardware/samd/1.8.2/libraries/LoRaWan and open LoRaWan.cpp and LoRaWan.h in a text editor.
Thank you for the suggestions!

2022-01-10 08:26 UTC, roel4ez commented
You'll need to add the file to mkdocs.yml > nav section to make it show up in the docs. Files are not added automatically

2022-01-10 10:17 UTC, danigian approved these changes
Approving for what it concerns the 'docs/tools/arduino-samples.md' file.

Please have a look at merge conflicts and what Roel wrote about mkdocs.yml

2022-01-10 12:34 UTC, roel4ez approved these changes

2022-01-10 12:34 UTC, merged